### ISSUE TITLE
Process killed after variant calling on short reads

### ISSUE THREAD

**Issue by elsasverris** [OmarOakheart/nPhase#17]
Hi Omar, I have tried to run nPhase on one sample of tetraploid potato. It takes a lot of time, but today it finally finished with variant calling on short reads. I have the output vcf file and also the vcf file with selected SNPs - but then the process stops. I tried to start the process again with nPhase partial, but it is killed again. I can't seem to figure out what the problem is, do you have an idea? I've attached the log file here.

Best, Elsa

[fullLog.txt](https://github.com/OmarOakheart/nPhase/files/7914281/fullLog.txt)

**Comment by OmarOakheart** [comment]
Hi again Elsa,

The potato genome is fairly large and typically highly heterozygous. In the nPhase paper I was able to run nPhase in reasonable amount of time only because I attempted to phase only one chromosome and I reduced the number of heterozygous SNPs used for phasing. Your process must be killed due to very high memory usage.

I recommend changing your reference file to only include one chromosome (and to run it as many times as you have chromosomes to phase). I also recommend subsetting your VCF to only include enough heterozygous SNPs to have a heterozygosity rate between 1% and 0.5% (1 heterozygous SNP every 100 and 200 bp).

You should then be able to run nphase partial with the vcf file that was generated by GATK during the nPhase pipeline steps you've already completed.

Quick tip for the process:

Copy the file in /outputFolder/VariantCalls/shortReads/samplename.SNPs.vcf to somewhere else (sampleName.preprocessed.SNPs.vcf)

```
cat sampleName.preprocessed.SNPs.vcf | grep "#" > sampleName.preprocessed.hetSNPs.vcf
cat sampleName.preprocessed.SNPs.vcf | grep -v "AF=1.00" >> sampleName.preprocessed.hetSNPs.vcf
cat sampleName.preprocessed.hetSNPs.vcf |  grep "#" > sampleName.chrIReduced.hetSNPs.vcf
cat sampleName.preprocessed.hetSNPs.vcf |  grep "chromosome01" | shuffle | head -n 1000 >> sampleName.chrIReduced.hetSNPs.vcf
```

Here I used head -n 1000, but you will want to replace 1000 by the number of SNPs required to obtain between 0.5% and 1% heterozygosity rate in that chrosome. (So for a 100 kb chromosome you want to keep 1kb of heterozygous SNPs, so head -n 1000).

You can then use that VCF file in nPhase partial. I think it would be OK to reuse the long reads mapped to the entire genome, etc. nPhase will simply interpret the other chromosomes as having 0 heterozygous SNPs and therefore ignore them. I don't believe it will heavily impact memory usage or running speed (though I have never tested and do not recall the exact workings of some of the program).

Let me know if I can clarify anything

Best,
Omar

**Comment by OmarOakheart** [comment]
Marking as closed due to inactivity
