### ISSUE TITLE
Number of haplotig

### ISSUE THREAD

**Issue by Lcornet** [OmarOakheart/nPhase#18]
I have a question concerning the nulber of haplotig.

I have a diploid genome of 173 contigs.
nphase predicted 757 haplotig.
After vizualisation, some contig have a high ploidy (frequently 4-6).

Is it the results of the options/threshold, should I specify something else (run with default option currently) ?

**Comment by OmarOakheart** [comment]
Do the results of nPhase look very fragmented?

For a diploid, if you're sure there is no aneuploidy and that there are always two haplotypes per chromosome, you might find it more interesting to run whatshap on your sample. Whatshap is designed specifically for diploid phasing and can take advantage of some properties of diploid genomes that nPhase doesn't take advantage of in phasing.

When nPhase predicts too many contigs, sometimes it means there isn't a high enough coverage, or the reads are too short or too errorful.

If you show me the visualisations generated by nPhase I can give you my opinion on how to interpret it.

**Comment by Lcornet** [comment]
[JERU_0.1_0.01_0.05_0_phasedVis.pdf](https://github.com/OmarOakheart/nPhase/files/8239372/JERU_0.1_0.01_0.05_0_phasedVis.pdf)

This is the visualization of nphase, it is quite fragmented yes.
Can it be a problem of polishing ? just run one round of pilon.

**Comment by OmarOakheart** [comment]
Oh, yes, almost 200 contigs, this is going to be difficult to visualize. So, ideally the best way to visualize it is actually with the _coverageVis.pdf plot, because this plot shows you, for each of these predicted haplotigs, how well-supported it is by reads. For example I'm curious about what that plot shows for contig_745

I have no idea what polishing does to phasing quality. My intuition is to worry that polishing can create noise. If you have a long read sequence AATAACAA, and the short reads support only AAGAACAA or AACAACAA, then the T in the long read sequence is wrong and needs to be corrected. But how will the polishing algorithm know how to correct it while maintaining the correct phase? The effects of polishing on phasing haven't been evaluated to my knowledge so I don't know if it's destructive, but I do think it could reasonably be argued that there may be a negative effect. That being said, maybe there's a positive effect from polishing that outweighs it.

I think the fragmentation is not that bad in a lot of the results you show. A lot of contigs, like on the top left, contig_131_pilon, this plot is almost empty which means that it's almost entirely homozygous and therefore there are only very short regions on which to make a prediction. It looks like there are maybe 13 haplotigs, and each of them could represent only a few SNPs total. There are a lot of contigs like this which seem to have very little heterozygosity and it causes the results to be bad, because there isn't enough heterozygosity to make good predictions.

In the bottom right, contig_96_pilon, you see there was a failure to phase, because most heterozygous SNPs are only represented by one haplotig, similar for the first half of contig_95_pilon to its left or contig_803_pilon above it. Since you have so many contigs I want to ask, are all of these sequences significantly different from each other? Is it possible that, for example, contig_95 and contig_96 (not necessarily these two, just an example) are different haplotypes of the same sequence, and the long reads were already "naturally phased" by mapping?

You might want to run nphase cleaning, which should simplify the results, but I think for a lot of the contigs here, either the results are coherent with a diploid and ready to be analyzed, or there is so little heterozygosity that they're a little too difficult to phase, maybe requiring more attention to phase properly if they're important enough to warrant it.

**Comment by Lcornet** [comment]
[JERU_0.1_0.01_0.05_0_coverageVis.pdf](https://github.com/OmarOakheart/nPhase/files/8239413/JERU_0.1_0.01_0.05_0_coverageVis.pdf)

This the cov vis plots. 

Ok, good to know about the impact of polishing. The only way is to test it with in without polishing. On this sample, i ahev a very good nanopore coverage (80 - 150), so the polishing step might not be useful. It can indeed bring noise.

The assembly was done by flye (i also test with CANU). I think that Flye and CANU already give haplotigs, not for all contigs but for some of them (at least Canu try to do an haplotype separation).
If I understand well, this means that if a diploid regions is assembled into to haplotigs, then there is no way to "reconciliate" them (or associate them) ? Is there an assembler that would be recommended before phasing ?

**Comment by OmarOakheart** [comment]
From my experience, CANU is more likely to create pseudo-phased assemblies than Flye, so I think CANU is the least good for this (or at least, canu makes it much more complicated in my opinion). Flye was usually good, but I found I had the most reasonable results with Smartdenovo when I used to do a lot of genome assemblies.

If you have a gold standard reference genome of your organism, you could try to do a dotplot between your de novo assembly and that gold standard reference. This way you can identify quickly and easily which contigs cover the same or similar regions, and you can decide to keep only one each time, which will reduce the number of contigs you map to during phasing and allow nPhase to phase the reads. Or you can consider that this means they were phased by the assembler and remove them both and consider that they already represent the phasing you are trying to obtain.

I would also test it without the polishing, nPhase was tested on examples with nanopore reads and no polishing. If the results are significantly worse (more fragmented), then we'll know we should suspect that maybe polishing plays an important role and we can investigate it with a benchmarking test.

For the results you show me, you can see on the bottom left, contig_786, the coverage is almost identical for both colors and between 75X and 100X, which is coherent with a total coverage of 150X-200X. This is an example of a contig that looks very well phased into a diploid sequence. Right underneath it, contig_805, you can see that in purple you have a haplotig that contains 150X worth of reads alone, and the light blue is basically just noise at less than 50X, that's not good phasing.

Then there are more complicated examples, like contig_735, where in the phased vis you showed me earlier it looks very fragmented. In the coverage plot, you can see that in the middle of the contig, there's a region where the coverage drops for one haplotig and increases for another, and that generally the phasing is good, there's just a little noise in the middle. This is the kind of "bad phasing" that the `nphase cleaning` process is supposed to try to fix. So if you run nPhase cleaning, look at the result on contigs like contig_735, contig_762, contig 428, contig_682, etc. These are supposed to be simplified, and for other contigs that look well-phased in the raw phasing results, they should not change, should not be collapsed.

Finally, based on these results, it doesn't look like there's any aneuploidy (though that might be due to this being a de novo assembly, for example if there are three copies of a chromosome but that they are so divergent the assembler created three contigs). If there is no aneuploidy, I think it makes more sense for you to use a tool like whatshap which will phase your sample explicitly as a diploid, rather than nPhase which tries to phase your sample with no assumptions in order to be able to phase polyploids and genomes with aneuploidies

**Comment by Lcornet** [comment]
Thanks for the explanation, really useful.

I have enough to continue by myself now. 
I 'll contact you back if i found major diffrence without polishing.

Thanks
