### ISSUE TITLE
Applying to contigs or chromosome-level scaffolds

### ISSUE THREAD

**Issue by OZTaekOppa** [OmarOakheart/nPhase#19]
Hi,

Thank you for sharing this tool with the community. After reading the manual and issues, I would like to use nPhase for my genome projects.

FYI,
Input data: PacBio (Sequel) with ~200X coverage (raw read N50 = ~14Kb)
Assembled contigs: ~1,000 cotigs (N50 = ~3Mb)
Chromosome-level scaffolds: 20 Chromosomes with Pore-C data (PromethION)
Trio data: Not available

Given the circumstances, I would like to ask your professional opinions on which stage would be better to use nPhase 1) "Assembled contigs" or 2) "Chromosome-level scaffolds"?

Thank you in advance!

**Comment by OmarOakheart** [comment]
Hello,

It would be best to use option #2. This way you minimize the number of haplotigs that are predicted. If you use 1000 contigs as a reference and you have a triploid, you will have 1000s of haplotigs as a final result, which sounds much more difficult to work with than if you use a reference with 20 scaffolds. I also recommend the scaffold option because the assembled contigs might be so numerous due to your _de novo_ assembly method trying to do some phasing on its own, which will make it a little harder for you to interpret results.

Unrelated: If you find that nPhase is too slow, you should know that I'm currently working on parallelizing the code and should be releasing a new, significantly more efficient version sometime this week.

**Comment by OZTaekOppa** [comment]
Thank you for your prompt reply. I will let you know after trying your suggestion. And, I am happy to wait for a few days more to test with the latest version.
Cheers!

**Comment by OmarOakheart** [comment]
I finally uploaded v1.2.0, it should be relatively faster to run the nPhase algorithm proper (nPhase partial/nphase algorithm, the full pipeline still takes however long it needs to take to run the different mapping and variant calling software).

I'm mentioning here just in case you were waiting for me to release the new version before launching nPhase

**Comment by OZTaekOppa** [comment]
Thanks. Will try it soon!

Apart from this, I have another question. 

Can I include more than one long-read dataset? I have two long-read from PacBio and Oxford Nanopore. Can I indicate them both respectively as 

--longReads /path/to/Individual_1_longReads.fastq.gz --longReadPlatform ont
--longReads /path/to/Individual_2_longReads.fastq.gz --longReadPlatform pacbio

If not, which long-read would be better for nPhase?

Any suggestion would be really appreciated! Cheers!

**Comment by OmarOakheart** [comment]
Including them both this way wouldn't work. I'm not sure which one would be better, it will mostly depend on the distribution of read lengths (and to some extent the quality). There haven't been any comparisons between ont and pacbio on the same sample done yet (due to lack of availability of data).

I think, something which may be done, is for you to manually map both datasets to the same reference and then manually stitch the SAM files together into one big hybrid read SAM file. In theory I don't imagine any problem with this being used as input to nPhase.

So this means running

```
ngmlr -t threadNumber -x longReadPlatform (ont or pacbio) -r reference.fasta -q longReads.fastq.gz -o output1.sam
ngmlr -t threadNumber -x longReadPlatform (ont or pacbio) -r reference.fasta -q longReads.fastq.gz -o output2.sam
```
Then manually removing the header from one of the two sam files and stitching them together into a big sam file of both together.

Once your new sam file is ready, run the following commands first:
```
samtools view -h -t reference.fasta -@ threadNumber -F 260 mergedSamFile.sam -o mappedReadsSamFile.sam
samtools sort mappedReadsSamFile.sam -@ threadNumber -o sortedHeaderSamFile.sam
samtools view sortedHeaderSamFile.sam -@ threadNumber -o sortedSamFile.sam
```

Then you can use sortedSamFile.sam as input to `nphase partial`

Let me know if any of these steps are unclear, and if you run into any issues with using this as input to nPhase. Hope this works well, it's an interesting idea!

**Comment by OZTaekOppa** [comment]
Testing it now but it got killed two times due to CPU and RAM issues.
I have used 12 CPU and 200Gb RAM for 3G diploid genome (100X Illumina PE reads and 50X ONT reads).
Do you have any idea how much computational cost would be required for this job?
Thanks all the time!

**Comment by OmarOakheart** [comment]
The genome is 3 gigabases? That will take a long time to phase, compared to the smaller (12.5Mb) genomes I've mainly used nPhase on.

Can you send me the file in the Log folder and any output you receive on the terminal, so that I can see which step it runs out of memory on? And can you confirm which version of nPhase you're using? This way I know if it's running with parallelization or not.

One solution, which I think might be necessary, is to split your reference into multiple smaller parts, for example if you have 10 scaffolds, make one .fasta file for each scaffold and run nPhase on the scaffolds individually, to greatly reduce the memory requirements, and then use a script to run them one at a time.

Does this mean you've decided to only use the ONT reads and not merge them with your Pacbio reads?

**Comment by OZTaekOppa** [comment]
Yes. It is a big genome. Most of the target genomes I am working with are 1Gb ~ 5Gb (di ~ polyploid). 

Since I am using $TMPDIR, it was not easy to retrieve the full log file.
This is the only output that I have retrieved. 

########################### Execution Started #############################
JobId:237871.flashmgr2
UserName:XXXXX
GroupName:qris-uq
ExecutionHost:fl016
###############################################################################
=>> PBS: job killed: mem 226632008kb exceeded limit 209715200kb
########################### Job Execution History #############################
JobId:237871.flashmgr2
UserName:XXXX
GroupName:qris-uq
JobName:BrahMP_nPhsV1
SessionId:7659
ResourcesRequested:mem=200gb,ncpus=12,place=free,walltime=336:00:00
ResourcesUsed:cpupercent=1200,cput=836:26:04,mem=226632008kb,ncpus=12,vmem=228579612kb,walltime=131:37:46
QueueUsed:General
AccountString:qris-uq
ExitStatus:271

Executed script: I have used the default script as described in your GitHub.

nphase pipeline --sampleName Individual_1 --reference /path/to/Individual_referenceGenome.fasta 
                --R1 /path/to/Individual_1_shortReads_R1.fastq.gz --R2 /path/to/Individual_1_shortReads_R2.fastq.gz
                --longReads /path/to/Individual_1_longReads.fastq.gz --longReadPlatform [ont|pacbio]
                --output /path/to/outputFolder --threads 8

nphase cleaning --sampleName Cleaning_1 --resultFolder /path/to/outputFolder/Individual_1
                --longReads /path/to/Individual_1_longReads.fastq.gz --threads 8

Re version, I am using the latest version 1.1.3.
Re the memory issue, I can increase up to 900Gb but am testing now with 400Gb (14 CPUs) for another dataset. 
Re ONT and PacBio, I have a few different datasets so am testing both options now. 
Re parallelization, I could try. It could work on the HPC (PBSpro environment). Any script for this?

Any suggestion would be really appreciated!

**Comment by OZTaekOppa** [comment]
Ok. Will do as you suggesed.

**Comment by OZTaekOppa** [comment]
This is what I see now.
Hope everything is updated properly.

(polyploidPhasing) XXXX@flashlite2:.../XXXXX/tmp/Brahman_Scripts> conda update -c oakheart nphase
Collecting package metadata (current_repodata.json): \ Unable to retrieve repodata (response: 404) for https://repo.anaconda.com/pkgs/free/noarch/current_repodata.js/ Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/oakheart/noarch/current_repodata.jsdone
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base conda

And, it is running now. 

Thank you so much for your help. 


# All requested packages already installed.

**Comment by OZTaekOppa** [comment]
Yes. It is the latest version. 

(polyploidPhasing) XXXXX@flashlite1:.../ASM_Mom/cuteSV/PBONT_Mrg> nphase --version
nPhase 1.2.0

And, two jobs are running.

                                                            Req'd  Req'd   Elap
Job ID          Username Queue    Jobname    SessID NDS TSK Memory Time  S Time
--------------- -------- -------- ---------- ------ --- --- ------ ----- - -----
242336.flashmgr XXXX General  BrahFP_nPh   1780   1  12  120gb 156:0 R 26:07    
242337.flashmgr XXXX General  BrahMP_nPh   8653   1  12  300gb 156:0 R 26:06

Cheers!

**Comment by OZTaekOppa** [comment]
It got killed due to a memory issue. 

###############################################################################
=>> PBS: job killed: mem 125928456kb exceeded limit 125829120kb
########################### Job Execution History #############################
JobId:242336.flashmgr2
UserName:XXXXX
GroupName:qris-uq
JobName:BrahFP_nPhs
SessionId:1780
ResourcesRequested:mem=120gb,ncpus=12,place=free,walltime=156:00:00
ResourcesUsed:cpupercent=1200,cput=588:55:57,mem=125928456kb,ncpus=12,vmem=127860796kb,walltime=119:45:58
QueueUsed:General
AccountString:qris-uq
ExitStatus:271
###############################################################################

The full log is here.
[fullLog.txt](https://github.com/OmarOakheart/nPhase/files/8849970/fullLog.txt)

**Comment by OZTaekOppa** [comment]
Even a 300Gb memory attempt was not successful. 

###############################################################################
=>> PBS: job killed: mem 328725124kb exceeded limit 314572800kb
########################### Job Execution History #############################
JobId:242337.flashmgr2
UserName:XXXXX
GroupName:qris-uq
JobName:BrahMP_nPhsV1
SessionId:8653
ResourcesRequested:mem=300gb,ncpus=12,place=free,walltime=156:00:00
ResourcesUsed:cpupercent=1200,cput=809:46:46,mem=328725124kb,ncpus=12,vmem=330668824kb,walltime=123:24:37
QueueUsed:General
AccountString:qris-uq
ExitStatus:271
###############################################################################

The full log is here.
[fullLog.txt](https://github.com/OmarOakheart/nPhase/files/8850963/fullLog.txt)

Looking forward to your reply!

Thanks.

**Comment by OZTaekOppa** [comment]
I checked both folders/files. The same files/folders were generated. 

drwxrws--- 2 XXXX Q4840RW 4096 Jun  7 17:17 Logs
drwxrws--- 4 XXXX Q4840RW 4096 Jun  2 13:19 Mapped
drwxrws--- 2 XXXX Q4840RW 4096 Jun  2 13:19 Overlaps
drwxrws--- 4 XXXX Q4840RW 4096 Jun  2 13:19 Phased
drwxrws--- 4 XXXX Q4840RW 4096 Jun  2 13:19 VariantCalls

XXXX@flashlite1:.../BraMomPhsV1/VariantCalls/longReads> ll
total 0

XXXX@flashlite1:.../BraMomPhsV1/VariantCalls/shortReads> ll
total 6381632
-rw-rw---- 1 XXXX Q4840RW 2078102995 Jun  7 16:28 BraMomPhsV1.hetSNPs.vcf
-rw-rw---- 1 XXXX Q4840RW 2080843029 Jun  7 16:28 BraMomPhsV1.SNPs.vcf
-rw-rw---- 1 XXXX Q4840RW    9488667 Jun  7 16:28 BraMomPhsV1.SNPs.vcf.idx
-rw-rw---- 1 XXXX Q4840RW 2366341035 Jun  7 16:25 BraMomPhsV1.vcf

XXXX@flashlite1:.../BraMomPhsV1/VariantCalls/shortReads> wc -l BraMomPhsV1.hetSNPs.vcf
8833120 BraMomPhsV1.hetSNPs.vcf

XXXX@flashlite1:.../PBONT_Mrg/BraMomPhsV1/Overlaps> ll
total 0

XXXX@flashlite1:.../PBONT_Mrg/BraMomPhsV1/Phased> ll
total 1
drwxrws--- 2 XXXX Q4840RW 4096 Jun  2 13:19 FastQ
drwxrws--- 2 XXXX Q4840RW 4096 Jun  2 13:19 Plots

XXXX@flashlite1:.../BraMomPhsV1/Phased/FastQ> ll
total 0

XXXX@flashlite1:.../BraMomPhsV1/Phased/Plots> ll
total 0


Do you still want me to proceed with the "nPhase partial"? 

Thanks.

**Comment by OmarOakheart** [comment]
It looks like it's failing on the very first step of the phasing algorithm, I suspect due to the size of the genome and the number of threads you run nPhase with. I would recommend running nPhase partial and reducing the number of threads with --threads.

If there is still a memory problem, it should happen pretty fast (maybe an hour after running?) and you should be able to reduce the number of threads again. I recommend running it first on the genome with less heterozygosity/lower coverage as a test to get an idea of the memory usage. Right now you use 12 threads I think, maybe try 6?

If reducing the number of threads doesn't work I could try to see if I can make changes to nPhase to fix the issue, but I don't have a large genome and dataset to test with. The next recommendation would be to run nPhase partial chromosome by chromosome. This means you take your reference and split it in chrI.fasta, chrII.fasta, etc. Then you run nPhase partial and use chrI.fasta as the reference sequence. This way the amount of data to process is much, much lower and the memory being used should also be lower (and if you run different chromosomes in parallel it'll also be faster). It does mean having to merge the results back together in the end though.

Hope this helps, let me know how it goes.

**Comment by OmarOakheart** [comment]
Marking as closed due to inactivity
