### ISSUE TITLE
NameError: name 'cachedSimilarities' is not defined

### ISSUE THREAD

**Issue by NaphatCode** [OmarOakheart/nPhase#24]
I keep getting this error which, I suspect that , terminate clustering iteration at 374 clusters every time, no matter what parameters I change. 

With this error, nPHASE still could produce output. But 374 clusters is too many, as I am expecting 3 clusters/haplotypes from this data.

Is this NameError normal? Is there any possible way to debug this on my end? Thank you in advance!

```
Traceback (most recent call last):
  File "/Users/naphat/miniconda3/miniconda3/envs/polyploidPhasing/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/naphat/miniconda3/miniconda3/envs/polyploidPhasing/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/naphat/miniconda3/miniconda3/envs/polyploidPhasing/lib/python3.8/site-packages/bin/nPhase.py", line 179, in cacheFiller
    cacheA = cachedSimilarities[cacheKey]
NameError: name 'cachedSimilarities' is not defined
```

**Comment by OmarOakheart** [comment]
Hello,

This error is not normal, without cachedSimilarities nPhase shouldn't work. I also don't currently see in what situation cachedSimilarities wouldn't be defined. I'm confused that it produced any output at all. Is it possible that 374 is close to the number of long reads you are using as an input? As if nPhase didn't even try phasing? Changing the parameters should also have an effect on results, there's definitely a problem here.

In https://github.com/OmarOakheart/nPhase/tree/master/example you will find some example data you can test nphase on, it should run quickly since it's very little data. Could you run this with the same command line and check if you get the same error?

Also let me know what you have with `nphase pipeline --version` just to be sure I'm looking at the correct code

**Comment by NaphatCode** [comment]
Thank you so much for your instantaneous support.   

I am using nPhase pipeline 1.2.0

My input that result in 374 clusters was actually quite inappropriate. I only have long read sequencing data, so I use same long read fastq for all three input fields (--longReads,--R1 and --R2.)  My data contains 5627 reads and *_variant.tsv shows that variants are clustered. So I implied by myself that maybe clustering terminate early. 


This is command line, log file and output for example data
`nphase pipeline --sampleName example --reference SaCe_Chr2.fasta --R1 SaCe_Chr2_SR_R1.fastq.gz  --R2 SaCe_Chr2_SR_R2.fastq.gz --longReads SaCe_Chr2_LR.fastq.gz --longReadPlatform ont --output /Users/naphat/SIRE698/10012023 --threads 8`

[fullLog_exampledata.txt](https://github.com/OmarOakheart/nPhase/files/10399741/fullLog_exampledata.txt)
[exampledata_output.zip](https://github.com/OmarOakheart/nPhase/files/10399770/exampledata_output.zip)

This is command line, log file, input summary and output of my data

`nphase pipeline --sampleName example --reference hg19.fasta --R1 NA23093.fastq.gz  --R2 NA23093.fastq.gz --longReads NA23093.fastq.gz --longReadPlatform ont --output /Users/naphat/SIRE698/10012023 --threads 8`

[NA23093_log.txt](https://github.com/OmarOakheart/nPhase/files/10399838/NA23093_log.txt)

[NA23093_longread_result.zip](https://github.com/OmarOakheart/nPhase/files/10399797/NA23093_longread_result.zip)

I sincerely appreciate your help and time for looking into the issue.

**Comment by OmarOakheart** [comment]
Ah, okay, I understand.

I think this issue is probably happening because of how you're trying to get around the lack of short reads. Right now nPhase runs GATK on your long reads as if they were short, and paired end with themselves.

I've never tested nPhase on only long reads, so no matter what I think you will have to look at your results with a skeptical eye. I think what you can try is to run a variant caller on your long reads. I haven't tested any long read variant callers so I can't make any recommendations, but here are three I know exist: https://github.com/kishwarshafin/pepper, https://github.com/WGLab/NanoCaller, https://github.com/pjedge/longshot

Once you've used one of these methods to generate a VCF file, you can use `nphase partial`. The idea behind `nphase partial` is to not run the entire pipeline, so for example if you want to do the mapping yourself with a different software, or the variant calling yourself, you can use `nphase partial` and just use your own inputs.

In this case, you would want to use `nphase partial --sampleName example --reference hg19.fasta --output /Users/naphat/SIRE698/10012023 --longReads NA23093.fastq.gz --vcf /path/to/custom/longReadVariantCalling.vcf --longReadPlatform ont --threads 8`

nPhase hasn't been tested on long reads only, so I'm not sure what to expect as a result, it will depend heavily on the accuracy of the variant calling.

Also, I notice your reference sequence is of the human genome. If you plan on running nPhase on a lot of data you should know that it doesn't scale very well with genome size and you may need to split the genome into parts in order to get results in a timely manner and without too much memory/CPU usage (though if your long reads really are only 5000 reads that's very little so that won't pose any problems). Don't hesitate to let me know if you need advice on how to reduce the time nPhase will take to run.

Let me know how it goes!

**Comment by NaphatCode** [comment]
Thank you again for encouragement to reach out! I'm very excited to try nPHASE out with my data. 
Long reads and VCF (by CLAIR3) are successfully loaded. But nPHASE partial seems to be unable to cluster the long reads at initiation of first loop. In what possible scenario could this happen? It would be very much appreciated if you could guide on this with your insight.

(polyploidPhasing) naphat@Naphats-MacBook-Pro NA23093 % nphase partial --sampleName NA23093 --reference hg19.fa --output /Users/naphat/SIRE698/10012023/Stargazer_v1.0.8/NA23093 --longReads NA23093.l1k_q9.pchop.cyp_rapid.fastq.gz --vcf merge_output.vcf --longReadPlatform ont --threads 8
Long reads successfully mapped to reference
Identified heterozygous SNPs in short read VCF
Extracted heterozygous SNP info based on short read VCF
Loading reads.
Reads loaded.
Loading context depth.
Context depth loaded
Split reads identified.
Split reads processed.
All reads processed.
Initializing cachedCluster
Filling cachedCluster with similarity information
Preparing initial similarity index
Starting clustering loop (0 sequences)
No clusters.
Initializing cachedCluster
Filling cachedCluster with similarity information
Preparing initial similarity index
Starting clustering loop (0 sequences)
No clusters.
Traceback (most recent call last):
  File "/Users/naphat/miniconda3/miniconda3/envs/polyploidPhasing/bin/nphase", line 11, in <module>
    sys.exit(main())
  File "/Users/naphat/miniconda3/miniconda3/envs/polyploidPhasing/lib/python3.8/site-packages/bin/nPhasePipeline.py", line 585, in main
    partialPipeline(args)
  File "/Users/naphat/miniconda3/miniconda3/envs/polyploidPhasing/lib/python3.8/site-packages/bin/nPhasePipeline.py", line 468, in partialPipeline
    phaseTool.nPhase(validatedSNPAssignmentsFile,args.strainName,contextDepthsFile,phasedPath,basePath,args.reference,args.minSim,args.minOvl,args.minLen,args.maxID,args.nPairs,int(args.threads))
  File "/Users/naphat/miniconda3/miniconda3/envs/polyploidPhasing/lib/python3.8/site-packages/bin/nPhase.py", line 593, in nPhase
    visDataTextFull=nPhaseFunctions.giveMeFullData(cleanAllClusters)
  File "/Users/naphat/miniconda3/miniconda3/envs/polyploidPhasing/lib/python3.8/site-packages/bin/nPhasePipelineFunctions.py", line 822, in giveMeFullData
    previouslySeen={sortedClusterLines[0][1]:i}
  File "/Users/naphat/miniconda3/miniconda3/envs/polyploidPhasing/lib/python3.8/site-packages/sortedcontainers/sortedlist.py", line 891, in __getitem__
    raise IndexError('list index out of range')
IndexError: list index out of range
(polyploidPhasing) naphat@Naphats-MacBook-Pro NA23093 % nphase partial --sampleName NA23093 --reference hg19.fa --output /Users/naphat/SIRE698/10012023/Stargazer_v1.0.8/NA23093 --longReads NA23093.l1k_q9.pchop.cyp_rapid.fastq.gz --vcf merge_output.vcf --longReadPlatform ont --threads 8

[fullLog.txt](https://github.com/OmarOakheart/nPhase/files/10405704/fullLog.txt)

**Comment by OmarOakheart** [comment]
Hello,

I think it's possible that nPhase doesn't know how to read the vcf file generated by CLAIR3, do you think you can send me a VCF file with the reads in /VariantCalling/shortReads/ of the output ? You can upload it here or email to me at omaroakheart@gmail.com

Or any VCF data generated by Clair3 really
